// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zzyfcqtedzztkwztvxqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp6eWZjcXRlZHp6dGt3enR2eHF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE2ODM5ODAsImV4cCI6MjA1NzI1OTk4MH0.gupAKE5J_lXC6O9KrpcKorcRI4NKUXPd4DdkXQfQPRk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);